/**
 * $Date: 2011-09-01 21:46:08 -0500 (Thu, 01 Sep 2011) $
 * $Revision: 140 $
 * $Author: robjackAdmin $
 * $Id: SpecialIllness_Stroke.drl 140 2011-09-02 02:46:08Z robjackAdmin $
 * 
 * @author Robert Jackson
 *
 * © 2011 Robert Jackson
 *
 */

package com.mycomism.edietitian



import org.tohu.Group;
import org.tohu.MultipleChoiceQuestion;
import org.tohu.MultipleChoiceQuestion.PossibleAnswer;
import org.tohu.Note;
import org.tohu.Question;
import org.tohu.Questionnaire;
import org.tohu.Answer;
import java.util.HashMap;
import java.util.Map;
import java.util.ArrayList;
import java.math.BigDecimal;
import com.mycomism.OtherRecommendation;
import com.mycomism.ExerciseRecommendation;
import com.mycomism.EatingRecommendation;
import com.mycomism.SFact;



